package com.ahmed.memoriar.utils

import com.ahmed.memoriar.R

const val EXTRA_GAME_NAME = "EXTRA_GAME_NAME"
const val EXTRA_BOARD_SIZE = "EXTRA_BOARD_SIZE"
val DEFAULT_ICONS = listOf(
  R.drawable.ic_apple,
  R.drawable.ic_aubergine,
  R.drawable.ic_bangladesh,
  R.drawable.ic_barn,
  R.drawable.ic_boots,
  R.drawable.ic_broccoli,
  R.drawable.ic_carrot,
  R.drawable.ic_carrotjuice,
  R.drawable.ic_corn,
  R.drawable.ic_environment,
  R.drawable.ic_factory,
  R.drawable.ic_fertilizer,
  R.drawable.ic_fertilizerblack,
  R.drawable.ic_gardening,
  R.drawable.ic_harvest,
  R.drawable.ic_house,
  R.drawable.ic_house1,
  R.drawable.ic_house2,
  R.drawable.ic_house_ecology,
  R.drawable.ic_leaves,
  R.drawable.ic_mushrooms,
  R.drawable.ic_nuclear_plant,
  R.drawable.ic_nucleus_geology,
  R.drawable.ic_radish,
  R.drawable.ic_rain,
  R.drawable.ic_rake,
  R.drawable.ic_saw,
  R.drawable.ic_shovel,
  R.drawable.ic_steak,
  R.drawable.ic_stock,
  R.drawable.ic_strawberry,
  R.drawable.ic_sun_cloud,
  R.drawable.ic_sunflower,
  R.drawable.ic_tree,
  R.drawable.ic_treeblack,
  R.drawable.ic_umbrella,
  R.drawable.ic_waste_barrel,
  R.drawable.ic_wheelbarrow,
  R.drawable.ic_windmill
//  R.drawable.ic_face,
//  R.drawable.ic_flower,
//  R.drawable.ic_gift,
//  R.drawable.ic_heart,
//  R.drawable.ic_home,
//  R.drawable.ic_lightning,
//  R.drawable.ic_moon,
//  R.drawable.ic_plane,
//  R.drawable.ic_school,
//  R.drawable.ic_send,
//  R.drawable.ic_star,
//  R.drawable.ic_work
)